<img src="<?= $this->basePath('img/doody/logo.png'); ?>" alt="Doody Suche" title="Doody Suche" id="logo"/>
<?php
$form->setAttribute('action', $this->url('application', ['action' => 'index']));
$form->setAttribute('id', 'searchbar');
$form->prepare();
?>
<?= $this->form()->openTag($form); ?>
<?= $this->formText($form->get('query')); ?>
<?= $this->formImage($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
